apiVersion: v1
kind: ServiceAccount
metadata:
  name: ldap-admin-key-generator
  namespace: openldap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ldap-admin-key-generator
  namespace: openldap
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ldap-admin-key-generator
  namespace: openldap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ldap-admin-key-generator
subjects:
  - kind: ServiceAccount
    name: ldap-admin-key-generator
    namespace: openldap