apiVersion: batch/v1
kind: Job
metadata:
  name: ldap-admin-key-generator
  namespace: openldap
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: ldap-admin-key-generator
      containers:
        - name: key-generator
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              if kubectl get secret ldap-passwords -o jsonpath='{.data.LDAP_ADMIN_PASSWORD}' 2>/dev/null | grep . >/dev/null && \
                 kubectl get secret ldap-passwords -o jsonpath='{.data.LDAP_CONFIG_PASSWORD}' 2>/dev/null | grep . >/dev/null; then
                  echo "Le secret existe déjà avec des clés valides, la génération est donc ignorée."
                  exit 0
              fi

              LDAP_ADMIN_PASSWORD="$(openssl rand -hex 16 | tr -d '\n')"
              LDAP_CONFIG_PASSWORD="$(openssl rand -hex 16 | tr -d '\n')"

              kubectl create secret generic ldap-passwords \
                --from-literal=LDAP_ADMIN_PASSWORD="$LDAP_ADMIN_PASSWORD" \
                --from-literal=LDAP_CONFIG_ADMIN_PASSWORD="$LDAP_CONFIG_PASSWORD" \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "Nouvelles valeurs générées et appliquées pour le secret des mots de passe LDAP."